INFO : The ligand of 181l_prepared.pdb has been extracted and saved in 'BNZ.pdb'
INFO : The ligand of methyl.pdb has been extracted and saved in 'FRG.pdb'
INFO : Performing a superimposition of bond [<Atom H1>, <Atom C1>] of the fragment on bond [<Atom C4>, <Atom H4>] of the core...
INFO : The following names of the fragment have been changed:
INFO : C1 --> G0
INFO : H2 --> G1
INFO : H3 --> G2
INFO : H4 --> G3
INFO : The result of core + fragment has been saved in 'growing_result.pdb'. This will be used to create the template file.
INFO : The result of core + fragment(small) has been saved in 'initialization_grow.pdb'. This will be used to initialise the growing.
INFO : 
============ Files selected ============
Control file: control_template.conf
PDB file: initialization_grow.pdb
Results folder name: growing_results/growing_output_0
Step: 0

INFO : 
•*´¨`*•.¸¸.•*´¨`*•.¸¸.•*´¨`*•.¸¸.•*´¨`*•.¸¸.••*´¨`*•.¸¸.•*´¨`*•.¸¸.•*´¨`*•.¸¸.•*´¨`*•.¸¸.•

/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
/home/dsoler/cleanPELE_rev/build_gnu/Pele_mpi: error while loading shared libraries: libboost_thread.so.1.66.0: cannot open shared object file: No such file or directory
INFO : 
•*´¨`*•.¸¸.•*´¨`*•.¸¸.•*´¨`*•.¸¸.•*´¨`*•.¸¸.••*´¨`*•.¸¸.•*´¨`*•.¸¸.•*´¨`*•.¸¸.•*´¨`*•.¸¸.•

INFO : SIMULATION growing_results/growing_output_0 COMPLETED!!! 
INFO : Looking structures to cluster in '/home/dsoler/repos/Ligand_growing/example/181L_methyl/growing_results/growing_output_0'
Traceback (most recent call last):
  File "/sNow/easybuild/centos/7.4.1708/Skylake/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/pandas-0.22.0-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 2372, in _infer_columns
    line = self._buffered_line()
  File "/sNow/easybuild/centos/7.4.1708/Skylake/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/pandas-0.22.0-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 2539, in _buffered_line
    return self._next_line()
  File "/sNow/easybuild/centos/7.4.1708/Skylake/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/pandas-0.22.0-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 2644, in _next_line
    orig_line = self._next_iter_line(row_num=self.pos + 1)
  File "/sNow/easybuild/centos/7.4.1708/Skylake/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/pandas-0.22.0-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 2704, in _next_iter_line
    return next(self.data)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../grow_for_pele.py", line 297, in <module>
    metricweights, nclusters, pele_eq_steps)
  File "../../grow_for_pele.py", line 267, in main
    column_number = Helpers.clusterizer.get_column_num(result, criteria, report)
  File "/home/dsoler/repos/Ligand_growing/Helpers/clusterizer.py", line 50, in get_column_num
    data = pd.read_csv(reports[0], sep='    ', engine='python')
  File "/sNow/easybuild/centos/7.4.1708/Skylake/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/pandas-0.22.0-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/sNow/easybuild/centos/7.4.1708/Skylake/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/pandas-0.22.0-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/sNow/easybuild/centos/7.4.1708/Skylake/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/pandas-0.22.0-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/sNow/easybuild/centos/7.4.1708/Skylake/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/pandas-0.22.0-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 1059, in _make_engine
    self._engine = klass(self.f, **self.options)
  File "/sNow/easybuild/centos/7.4.1708/Skylake/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/pandas-0.22.0-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 2086, in __init__
    self.columns, self.num_original_columns = self._infer_columns()
  File "/sNow/easybuild/centos/7.4.1708/Skylake/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/pandas-0.22.0-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 2394, in _infer_columns
    "No columns to parse from file")
pandas.errors.EmptyDataError: No columns to parse from file
